name: push-master

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Use Cache
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Get dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        go mod download
    - name: Run Test
      run: make test
    - name: Build
      run: make build
    - name: Save Artifact
      uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: build/*/vsort*
  smoke-test:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        include:
          - os: macos-latest
            osarch: darwin-amd64
            extention: ''
          - os: windows-latest
            osarch: windows-amd64
            extention: '.exe'
          - os: ubuntu-latest
            osarch: linux-amd64
            extention: ''
      fail-fast: false
    needs: [build]
    runs-on: "${{ matrix.os }}"
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: binaries
          path: binaries
      - name: Smoke Test
        run: |
          chmod a+x "binaries/vsort-${{ matrix.osarch }}/vsort${{ matrix.extention }}"
          binaries/vsort-${{ matrix.osarch }}/vsort${{ matrix.extention }} "-h"
